package me.neko.nzhelper.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF4A672D)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFCBEEA5)
val OnPrimaryContainerLight = Color(0xFF121F00)
val SecondaryLight = Color(0xFF57624A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDBE7C9)
val OnSecondaryContainerLight = Color(0xFF151E0B)
val TertiaryLight = Color(0xFF386664)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBCECEA)
val OnTertiaryContainerLight = Color(0xFF00201F)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF9FAEF)
val OnBackgroundLight = Color(0xFF1A1C16)
val SurfaceLight = Color(0xFFF9FAEF)
val OnSurfaceLight = Color(0xFF1A1C16)
val SurfaceVariantLight = Color(0xFFE1E4D5)
val OnSurfaceVariantLight = Color(0xFF44483D)
val OutlineLight = Color(0xFF75796C)
val OutlineVariantLight = Color(0xFFC5C8BA)
val ScrimLight = Color(0xFF000000)
val InverseSurfaceLight = Color(0xFF2F312A)
val InverseOnSurfaceLight = Color(0xFFF1F2E6)
val InversePrimaryLight = Color(0xFFAFD18C)
val SurfaceDimLight = Color(0xFFDADBD0)
val SurfaceBrightLight = Color(0xFFF9FAEF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF3F4E9)
val SurfaceContainerLight = Color(0xFFEEEFE3)
val SurfaceContainerHighLight = Color(0xFFE8E9DE)
val SurfaceContainerHighestLight = Color(0xFFE2E3D8)

val PrimaryDark = Color(0xFFAFD18C)
val OnPrimaryDark = Color(0xFF213600)
val PrimaryContainerDark = Color(0xFF334E17)
val OnPrimaryContainerDark = Color(0xFFCBEEA5)
val SecondaryDark = Color(0xFFBFCBAD)
val OnSecondaryDark = Color(0xFF2A331E)
val SecondaryContainerDark = Color(0xFF404A33)
val OnSecondaryContainerDark = Color(0xFFDBE7C9)
val TertiaryDark = Color(0xFFA0CFCC)
val OnTertiaryDark = Color(0xFF003735)
val TertiaryContainerDark = Color(0xFF1F4E4B)
val OnTertiaryContainerDark = Color(0xFFBCECEA)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF12140E)
val OnBackgroundDark = Color(0xFFE2E3D8)
val SurfaceDark = Color(0xFF12140E)
val OnSurfaceDark = Color(0xFFE2E3D8)
val SurfaceVariantDark = Color(0xFF44483D)
val OnSurfaceVariantDark = Color(0xFFC5C8BA)
val OutlineDark = Color(0xFF8F9285)
val OutlineVariantDark = Color(0xFF44483D)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFE2E3D8)
val InverseOnSurfaceDark = Color(0xFF2F312A)
val InversePrimaryDark = Color(0xFF4A672D)
val SurfaceDimDark = Color(0xFF12140E)
val SurfaceBrightDark = Color(0xFF383A32)
val SurfaceContainerLowestDark = Color(0xFF0C0F09)
val SurfaceContainerLowDark = Color(0xFF1A1C16)
val SurfaceContainerDark = Color(0xFF1E201A)
val SurfaceContainerHighDark = Color(0xFF282B24)
val SurfaceContainerHighestDark = Color(0xFF33362E)

val AmoledBlack = Color(0xFF000000)

val LightColorScheme: ColorScheme = lightColorScheme(
    primary = PrimaryLight,
    onPrimary = OnPrimaryLight,
    primaryContainer = PrimaryContainerLight,
    onPrimaryContainer = OnPrimaryContainerLight,
    secondary = SecondaryLight,
    onSecondary = OnSecondaryLight,
    secondaryContainer = SecondaryContainerLight,
    onSecondaryContainer = OnSecondaryContainerLight,
    tertiary = TertiaryLight,
    onTertiary = OnTertiaryLight,
    tertiaryContainer = TertiaryContainerLight,
    onTertiaryContainer = OnTertiaryContainerLight,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight,
    scrim = ScrimLight,
    inverseSurface = InverseSurfaceLight,
    inverseOnSurface = InverseOnSurfaceLight,
    inversePrimary = InversePrimaryLight,
    surfaceDim = SurfaceDimLight,
    surfaceBright = SurfaceBrightLight,
    surfaceContainerLowest = SurfaceContainerLowestLight,
    surfaceContainerLow = SurfaceContainerLowLight,
    surfaceContainer = SurfaceContainerLight,
    surfaceContainerHigh = SurfaceContainerHighLight,
    surfaceContainerHighest = SurfaceContainerHighestLight,
)

val DarkColorScheme: ColorScheme = darkColorScheme(
    primary = PrimaryDark,
    onPrimary = OnPrimaryDark,
    primaryContainer = PrimaryContainerDark,
    onPrimaryContainer = OnPrimaryContainerDark,
    secondary = SecondaryDark,
    onSecondary = OnSecondaryDark,
    secondaryContainer = SecondaryContainerDark,
    onSecondaryContainer = OnSecondaryContainerDark,
    tertiary = TertiaryDark,
    onTertiary = OnTertiaryDark,
    tertiaryContainer = TertiaryContainerDark,
    onTertiaryContainer = OnTertiaryContainerDark,
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = BackgroundDark,
    onBackground = OnBackgroundDark,
    surface = SurfaceDark,
    onSurface = OnSurfaceDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    outline = OutlineDark,
    outlineVariant = OutlineVariantDark,
    scrim = ScrimDark,
    inverseSurface = InverseSurfaceDark,
    inverseOnSurface = InverseOnSurfaceDark,
    inversePrimary = InversePrimaryDark,
    surfaceDim = SurfaceDimDark,
    surfaceBright = SurfaceBrightDark,
    surfaceContainerLowest = SurfaceContainerLowestDark,
    surfaceContainerLow = SurfaceContainerLowDark,
    surfaceContainer = SurfaceContainerDark,
    surfaceContainerHigh = SurfaceContainerHighDark,
    surfaceContainerHighest = SurfaceContainerHighestDark,
)